version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8000
    depends_on:
      - backend
    networks:
      - auslex-network

  backend:
    image: python:3.9-slim
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install fastapi uvicorn transformers torch &&
             python -m uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - auslex-network

networks:
  auslex-network:
    driver: bridge 