name: CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck
      - run: npm test -- -i
      - name: Conditional eval
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EVAL_ENFORCE: '0'
        run: |
          if [ -n "$OPENAI_API_KEY" ]; then npm run eval || true; fi
      - name: Upload eval artifacts
        if: ${{ always() && secrets.OPENAI_API_KEY != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: eval-artifacts
          path: |
            eval/results.json
            eval/results.csv
          if-no-files-found: ignore

