name: DB Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Install pg client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Dump database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then echo "DATABASE_URL not set"; exit 0; fi
          F=/tmp/auslex_snapshot_$(date -u +%F).sql.gz
          pg_dump --no-owner --if-exists --quote-all-identifiers "$DATABASE_URL" | gzip > $F
          echo "SNAP=$F" >> $GITHUB_ENV
      - name: Upload artifact
        if: env.SNAP != ''
        uses: actions/upload-artifact@v4
        with:
          name: db-snapshot-${{ github.run_id }}
          path: ${{ env.SNAP }}
          retention-days: 14

