name: Nightly Eval

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Run eval
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EVAL_ENFORCE: '1'
          EVAL_MIN_ACCURACY: ${{ vars.EVAL_MIN_ACCURACY || '0.8' }}
        run: npm run eval
      - name: Upload eval artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-eval-${{ github.run_id }}
          path: |
            eval/results.json
            eval/results.csv
          retention-days: 7
      - name: Post summary comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SUMMARY=$(jq -r '.summary | "accuracy=" + (.accuracy|tostring) + ", medianMs=" + (.medianMs|tostring) + ", meanMs=" + (.meanMs|tostring) + ", passed=" + (.passed|tostring) + "/" + (.total|tostring)' eval/results.json)
          ISSUE_NUM=$(gh issue list --state open --search "Eval Results in:title" --json number,title | jq -r '.[0].number // empty')
          if [ -z "$ISSUE_NUM" ]; then gh issue create -t "Eval Results" -b "$SUMMARY"; else gh issue comment $ISSUE_NUM -b "$SUMMARY"; fi

